lms/src/main/java/ukma/baratheons/lms/entity/ConfirmActionType.java
package ukma.baratheons.lms.entity;

import ukma.baratheons.lms.anorm.Id;

public enum ConfirmActionType {
	
	
	registration_user("registration_user"), reset_password("reset_password"), new_task("new_task"), new_task_with_reg("new_task_with_reg");
	
	@Id
	private final String value;
	
	private ConfirmActionType(String value){
		this.value = value;
	}
	
	
}

lms/src/main/java/ukma/baratheons/lms/entity/Equipment.java
package ukma.baratheons.lms.entity;

import ukma.baratheons.lms.anorm.Base;
import ukma.baratheons.lms.anorm.DataBaseField;
import ukma.baratheons.lms.anorm.Embedded;
import ukma.baratheons.lms.anorm.Entity;
import ukma.baratheons.lms.anorm.Id;
import ukma.baratheons.lms.anorm.Transient;
import ukma.baratheons.lms.query.Table;


@Entity(Table.EquipmentTable.TABLE_NAME)
public class Equipment {

	@Id
	@Transient
	@DataBaseField(Table.EquipmentTable.ID)
	private Long id;
	
	@Base
	@DataBaseField(Table.EquipmentTable.LOCAL_NAME)
	private String localNumber;
	
	@DataBaseField(Table.EquipmentTable.IS_DECOMMISSIONED)
	private boolean isDecommissioned;
	
	@DataBaseField(Table.EquipmentTable.TYPE)
	@Embedded(value=EquipmentType.class, nullable=false)
	@Base
	private EquipmentType eqptType;
	
	@DataBaseField(Table.EquipmentTable.ROOM)
	@Base
	@Embedded(value=Room.class, nullable=true)
	private Room room;
	
	public Equipment(){
	}

	public Equipment(String localNumber) {
		this.localNumber = localNumber;
	}

	public Equipment(long id, boolean isDecommissioned,
					 long eqptTypeId, Room room) {
		this.id = id;
		this.isDecommissioned = isDecommissioned;
		this.eqptType.setId(eqptTypeId);
		this.room = room;
	}

	public Equipment(boolean isDecommissioned,
			long eqptTypeId, Room room) {
		this.isDecommissioned = isDecommissioned;
		this.eqptType.setId(eqptTypeId);
		this.room = room;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getLocalNumber() {
		return localNumber;
	}

	public void setLocalNumber(String localNumber) {
		this.localNumber = localNumber;
	}

	public boolean isDecommissioned() {
		return isDecommissioned;
	}

	public void setDecommissioned(boolean isDecommissioned) {
		this.isDecommissioned = isDecommissioned;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public void setEqptType(EquipmentType eqptType) {
		this.eqptType = eqptType;
	}
	
	public Room getRoom(){
		return room;
	}
	
	public EquipmentType getEqptType(){
		return eqptType;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Equipment other = (Equipment) obj;
		if (eqptType == null) {
			if (other.eqptType != null)
				return false;
		} else if (!eqptType.equals(other.eqptType))
			return false;
		if (localNumber == null) {
			if (other.localNumber != null)
				return false;
		} else if (!localNumber.equals(other.localNumber))
			return false;
		if (room == null) {
			if (other.room != null)
				return false;
		} else if (!room.getNumber().equals(other.room.getNumber()))
			return false;
		return true;
	}
	
}

lms/src/main/java/ukma/baratheons/lms/entity/UserAction.java
package ukma.baratheons.lms.entity;

public enum UserAction {
AccepdedTask,DeclinedTask,CompletedTask,RightsChanded
}

lms/src/main/java/ukma/baratheons/lms/controller/ApiController.java
package ukma.baratheons.lms.controller;

import java.util.ArrayList;
import java.sql.SQLException;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import ukma.baratheons.lms.anorm.Operator;
import ukma.baratheons.lms.entity.Comment;
import ukma.baratheons.lms.entity.Equipment;
import ukma.baratheons.lms.entity.Room;
import ukma.baratheons.lms.entity.Task;
import ukma.baratheons.lms.entity.TaskType;
import ukma.baratheons.lms.entity.User;
import ukma.baratheons.lms.query.Table;
import ukma.baratheons.lms.service.*;

//Controller for AJAX requests
@RestController
@RequestMapping("/api")
public class ApiController {

	@Autowired
	private UserAdministrationService userService;

	@Autowired
	private EquipmentService eqptService;

	@Autowired
	private CommentService commentService;

	@Autowired
	private EquipmentService equipmentService;

	@Autowired
	private RoomService roomService;

	@Autowired
	private TaskManagementService taskService;

	private static final Logger LOGGER = LogManager
			.getLogger(TaskController.class);
	
	/**
	 * 
	 * @return List of all Rooms
	 */
	public List<Room> getAllRooms() {

		return null;
	}

	@RequestMapping(path = "/staffproductivity")
	public List<User> getStaffProductiity() {
		List<User> list = userService.getStaffProductivityReport();
		return list;
	}

	/**
	 * 
	 * @param room
	 * @return List of Equipment belonging to room
	 */
	public List<Equipment> getEquipmentByRoom(Room room) {

		return null;
	}

	/**
	 * 
	 * @param room
	 * @return List of Tasks belonging to room
	 */
	public List<Task> getTasksByRoom(Room room) {

		return null;
	}

	/**
	 * 
	 * @param room
	 * @return List of Tasks belonging to User of type Staff Member
	 */
	public List<Task> getTasksByStaffMember(Room room) {

		return null;
	}

	/**
	 * 
	 * @param equipment
	 * @return List of Tasks attached to equipment with status Opened
	 */
	public List<Task> getOpenedTasksByEquipment(Equipment equipment) {

		return null;
	}

	/**
	 * 
	 * @return List of Tasks belonging to User of type Client
	 */
	public List<Task> getTasksByUser() {
		return null;
	}

	/**
	 * 
	 * @param type
	 * @return
	 */
	public List<Task> getTasksByUser(TaskType type) {
		return null;
	}

	// returns of all tasks which were attached to this task
	public List<Comment> getCommentsByTasks(Task task) {
		return null;
	}

	@RequestMapping(value = "/users_filtered", method = RequestMethod.POST)
	public List<User> getUsersFiltered(@RequestBody int filters,
			@RequestParam(value = "chief", required = false) String chief) {
		String chiefAdmin = null;

		if (chief != null) {
			chiefAdmin = "chief";
		}
		List<User> users = userService.getUsersFiltered(filters, chiefAdmin);
		return users;
	}

	@RequestMapping(value = "/listEquipment", method = RequestMethod.POST)
	public List<Equipment> getEquipmentByRoom(@RequestBody int roomId) {
		List<Equipment> equipments = eqptService.getEquipmentByRoom(roomId);
		return equipments;
	}

	@RequestMapping(value = "/listEquipmentEager", method = RequestMethod.POST)
	public List<Equipment> getEquipmentByRoomEager(@RequestBody int roomId) {
		List<Equipment> equipments = eqptService
				.getEquipmentEager(new ukma.baratheons.lms.anorm.Filter(
						Table.EquipmentTable.TABLE_NAME, Table.EquipmentTable.ROOM, Operator.EQ, roomId));
		return equipments;
	}

	@RequestMapping(value = "/listComment", method = RequestMethod.POST)
	public List<String> getCommentByEquipment(@RequestBody int eqptId) {
		List<Comment> comments = commentService.getCommentsByEqpt(eqptId);
		List<String> str = new ArrayList<String>();
		for (Comment c : comments)
			str.add(c.getDate().toString().substring(0, 16) + " - "
					+ c.getText());
		return str;
	}

	@RequestMapping(value = "/isRegistered/{email}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public Boolean isValid() {
		return true;
	}

	@RequestMapping(value = "/saveEquipment", method = RequestMethod.POST)
	public Equipment saveEquipment(@RequestBody Equipment equipment) {
		System.out.println(equipment.getLocalNumber()+"#%&@%%^@^%^%");
		try {
			equipmentService.add(equipment);
		} catch (SQLException e) {
			LOGGER.error("Adding equipment");
			return null;
		}
		LOGGER.info("Added equipment id: " + equipment.getId());
		return equipment;
	}

	@RequestMapping(value = "/updateEquipment", method = RequestMethod.POST)
	public Equipment updateEquipment(@RequestBody Equipment equipment) {
		try {
			equipmentService.edit(equipment);
		} catch (SQLException e) {
			LOGGER.error("Updating equipment id: " + equipment.getId());
			return null;
		}
		LOGGER.info("Updated equipment id: "+equipment.getId());
		return equipment;
	}

	@RequestMapping(value = "/updateRoom", method = RequestMethod.POST)
	public Room updateRoom(@RequestBody Room room) {
		try {
			roomService.update(room);
		} catch (SQLException e) {
			LOGGER.error("Updating room id: " + room.getId());
			return null;
		}
		LOGGER.info("Updated room id: " + room.getId());
		return room;
	}

	@RequestMapping(value = "/addRoom", method = RequestMethod.POST)
	public Room saveRoom(@RequestBody Room room) {
		try {
			roomService.create(room);
		} catch (SQLException e) {
			LOGGER.error("Adding a room");
			return null;
		}
		LOGGER.info("Added room id: " + room.getId());
		return room;
	}

	@RequestMapping(value = "/deleteRoom", method = RequestMethod.POST)
	public boolean deleteRoom(@RequestBody Room room) {
		try {
			roomService.delete(room);
		} catch (SQLException e) {
			LOGGER.error("deleting room id: " + room.getId());
			return false;
		}
		LOGGER.info("Deleted room id: " + room.getId());
		return true;
	}
}

lms/src/main/java/ukma/baratheons/lms/controller/EquipmentController.java
package ukma.baratheons.lms.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import ukma.baratheons.lms.entity.Equipment;
import ukma.baratheons.lms.entity.EquipmentType;
import ukma.baratheons.lms.entity.Room;
import ukma.baratheons.lms.service.EquipmentService;
import ukma.baratheons.lms.service.RoomService;

@Controller
@RequestMapping("/equipment")
public class EquipmentController {
	
	@Autowired
	RoomService roomService;
	
	@Autowired 
	EquipmentService equipmentService;
	
	@RequestMapping(path="/list")
	public String listEquipment(Model model){
		List<Room>rooms= roomService.getAllRooms();
		model.addAttribute("rooms", rooms);
		List<EquipmentType>eqptTypes = equipmentService.getEquipmentTypes();
		model.addAttribute("eqptTypes", eqptTypes);
		List<Equipment>equipment = equipmentService.getEquipmentEager(null);
		
		model.addAttribute("equipments", equipment);
		return "equipment";
	}	

}

lms/src/main/java/ukma/baratheons/lms/controller/LoginController.java
package ukma.baratheons.lms.controller;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import ukma.baratheons.lms.entity.Room;
import ukma.baratheons.lms.entity.TaskType;
import ukma.baratheons.lms.service.RoomService;
import ukma.baratheons.lms.service.TaskManagementService;
import ukma.baratheons.lms.service.UserAdministrationService;
import ukma.baratheons.lms.util.BitUtils;
import ukma.baratheons.lms.util.MD5;

@Controller
public class LoginController {

	private static final Logger LOGGER = LogManager
			.getLogger(LoginController.class);

	@Autowired
	private UserAdministrationService userService;

	@Autowired
	private RoomService roomService;

	@Autowired
	private TaskManagementService taskService;

	/**
	 * main page The main page of site.
	 * 
	 * @param RequestMapping
	 *            URL of main page
	 * @param error
	 *            true if User write wrong login or password
	 * @param attention
	 *            true if User go to page, which is designed for authenticated
	 *            users
	 * @param login
	 *            change lastOnline attribute of User
	 * @param createTask
	 *            not NULL if user just create task
	 * @return name of main page
	 * */
	@RequestMapping(value = { "/", "/welcome" }, method = RequestMethod.GET)
	public String welcomePage(
			Model model,
			SecurityContextHolderAwareRequestWrapper request,
			@RequestParam(value = "error", required = false) String error,
			@RequestParam(value = "attention", required = false) String attention,
			@RequestParam(value = "login", required = false) String login,
			@RequestParam(value = "createTask", required = false) String createTask) {

		request.getSession(true).setAttribute("reset_sec", MD5.getRandomHash());
		
		model.addAttribute("reset_sec",
				request.getSession().getAttribute("reset_sec"));
		
		request.getSession().setAttribute("create_task_sec", MD5.getRandomHash());
		
		model.addAttribute("create_task_sec",
				request.getSession().getAttribute("create_task_sec"));

		List<Room> rooms = roomService.getRoomsLazy(null);
		model.addAttribute("rooms", rooms);
		ArrayList<TaskType> types = taskService.getTaskTypes();
		model.addAttribute("typesTask", types);
		if (request.isRequestedSessionIdValid()) {
			if (request.isUserInRole("admin")) {
				if (BitUtils.isBitSet(1,
						userService.getUserByEmail(request.getRemoteUser())
								.getRights())) {
					model.addAttribute("role", "Chief Admin");
				} else {
					model.addAttribute("role", "Admin");
				}
			} else if (request.isUserInRole("user")) {
				model.addAttribute("role", "Client");
			} else if (request.isUserInRole("laborant")) {
				model.addAttribute("role", "Staff member");
			}
		}

		if (error != null) {
			model.addAttribute("msg", "Login/password is invalid");
		}

		if (attention != null) {
			model.addAttribute("msg", "First log in, please");
		}

		if (login != null) {
			try {
				userService.updateLastOnline(request.getRemoteUser());
			} catch (SQLException e) {
				LOGGER.error("Updating lastOnline for user id: "
						+ request.getRemoteUser());
			}
		}

		if (createTask != null) {
			model.addAttribute("createTask",
					"Please check your email and confirm the task!");
		}

		LOGGER.info("Main page");
		return "main";
	}

	/**
	 * Deny page - if authenticated users go to page, which is designed for
	 * another role.
	 * 
	 * @param RequestMapping
	 *            URL of deny page
	 * @return name of deny page
	 * */
	@RequestMapping(value = "/403", method = RequestMethod.GET)
	public String accessDenied(Model model) {
		LOGGER.info("403 page");
		model.addAttribute("title", "Oooops!");
		model.addAttribute("head", "403 Forbidden");
		model.addAttribute("img", "/lms/resources/img/deny.png");
		model.addAttribute("description", "You can not access to this page");
		return "message";
	}

	/**
	 * Error page - if users go to page, which doesn't exist.
	 * 
	 * @param RequestMapping
	 *            URL of error page
	 * @return name of error page
	 * */
	@RequestMapping(value = "/404", method = RequestMethod.GET)
	public String error404(Model model) {
		LOGGER.info("404 page");
		model.addAttribute("title", "Oooops!");
		model.addAttribute("head", "404 Not Found");
		model.addAttribute("img", "/lms/resources/img/deny.png");
		model.addAttribute("description", "This page not exist");
		return "message";
	}

	/**
	 * Error page - server error.
	 * 
	 * @param RequestMapping
	 *            URL of error page
	 * @return name of error page
	 * */
	@RequestMapping(value = "/500", method = RequestMethod.GET)
	public String error500(Model model) {
		LOGGER.error("500 page");
		model.addAttribute("title", "Oooops!");
		model.addAttribute("head", "500 Server Error");
		model.addAttribute("img", "/lms/resources/img/deny.png");
		model.addAttribute(
				"description",
				"Sorry, but the server encountered an u"
						+ "nexpected condition which prevented it <br/> from fulfilling the "
						+ "request. Please, return to main page and try again.");
		return "message";
	}
}

lms/src/main/java/ukma/baratheons/lms/controller/RoomController.java
package ukma.baratheons.lms.controller;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import ukma.baratheons.lms.entity.Room;
import ukma.baratheons.lms.entity.User;
import ukma.baratheons.lms.service.RoomService;
import ukma.baratheons.lms.service.UserAdministrationService;

@Controller
@RequestMapping("/rooms")
public class RoomController {
	
	@Autowired
	private RoomService roomService;
	
	@Autowired 
	UserAdministrationService userService;

	@RequestMapping(path="/list")
	public String listRooms(Model model) throws SQLException {
		List<Room>rooms = roomService.getAllRooms();
		model.addAttribute("rooms", rooms);
		List<User>staff = userService.getStaff();
		model.addAttribute("staff", staff);
		return "rooms";
	}
}

lms/src/main/webapp/WEB-INF/views/equipment.jsp
<%@include file="header.jsp"%>

<!-- Top of page -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1> LMS </h1>
            <h3>Here you can view, add and edit equipments.</h3>
            <br /> 
            <a href="#list_equipments" class="btn btn-dark btn-lg">
            View equipments
            </a>
        </div>
    </header>
    
    <hr />

<section id="list_equipments">
<div class="container" style="max-width:300px;" align="center">
  <h1 align="center">Equipment list</h1>
  <hr size="5"/>
  <div class="form-group">
    <label for="room">Select room</label>
    <select class="form-control" id="room">
	<option value="">All</option>
      <option value="n">Not Attached</option>
      <c:forEach items="${rooms}" var="room">
        <option value="${room.id}">${room.number}</option>
      </c:forEach>
    </select>
  </div>
</div>
</section>

<div class="container" align="right" style="max-width:80%;">
  <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" onclick="addEqpm()">Add equipment</button>
</div>

<div style="padding: 20px 20px 20px 20px">
  <div class="container">
    <table class="table table-hover" id = "eqTable">
      <thead id = "tableHead">
        <tr>
			<td>Id</td>
			<td>Room</td>
	        <td>Local Number</td>
	        <td>Type</td>
	        <td>Decommissioned</td>
	        <td data-orderable="false">Edit</td>
			<td>Room Id</td>
        </tr>
      </thead>
      <tbody>
      	<c:forEach items="${equipments}" var="equipment">
      		<tr>
      			<td>${equipment.id}</td>
      			<td>${equipment.room.number}</td>
      			<td>${equipment.localNumber}</td>
      			<td>${equipment.eqptType.name}</td>
      			<c:if test="${equipment.decommissioned==true}">
      				<td><img src="<c:url value="/resources/img/no.png" />" height="25" width="25"></td>
      			</c:if>
      			<c:if test="${equipment.decommissioned!=true}">
      				<td><img src="<c:url value="/resources/img/yes.png" />" height="25" width="25"></td>
      			</c:if>
      			<td><button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" onclick="edit(${equipment.localNumber}, ${equipment.id}, ${equipment.eqptType.id}, ${equipment.room.id}, ${equipment.decommissioned})">Edit</button></td>
      			<td>${equipment.room.id}</td>
      		</tr>
      	</c:forEach>
      </tbody>
    </table>
	<input type="text" id="row" style="display: none">
  </div>
</div>

<!--Modal window for the equipments' editing and adding-->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="editWindow" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
<form method="post" action="#" id="myform">
  <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" align="center" id="label">Edit equipment</h4>
      </div>

      <div class="modal-body">
        <div class="form-group">
          <label for="mNum">Local number:</label>
		  <input type="text" class="form-control" id="mId" style="display: none">
          <input type="text" class="form-control" id="mNum" maxlength="10" required>
        </div>
        <div class="form-group">
          <label for="mType">Type:</label>
          <select class="form-control" id="mType" required>
			<c:forEach items="${eqptTypes}" var="type">
              <option value="${type.id}">${type.name}</option>
            </c:forEach>
          </select>
        </div>
        <div class="form-group">
          <label for="mRoom">Room:</label>
          <select class="form-control" id='mRoom' required>
			<option value="-">Not Attached</option>
            <c:forEach items="${rooms}" var="room">
              <option value="${room.id}">${room.number}</option>
            </c:forEach>
          </select>
        </div>
        <div class="form-group" id="decomChBox">
          <label for="mDecom">isDecommissioned:</label>
          <input type="checkbox" id="mDecom">
        </div>
      </div>

      <div class="modal-footer">
        <div class="form-group">
          <button type="submit" class="btn btn-primary" id="save" >Save</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
  </div>
</div>
</form>    
    </div>
		</div>

<!--Modal window (error)-->
<div class="modal fade error" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="error" aria-hidden="true">
	<div class="modal-dialog modal-sm">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        		<h4 class="modal-title">Error</h4>
      		</div>
      		<div class="modal-body">
       			<p id="errMessage">error</p>
      		</div>
      		<div class="modal-footer">
         		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      		</div>
    	</div>
 	</div>
</div>

<script>
//cleaning edit window fields
	function addEqpm(){
		$('#label').text("Add equipment"); 
		document.getElementById('mId').value = "";
		document.getElementById('mNum').value = "";
		document.getElementById('mType').value = "";
		document.getElementById('mRoom').value = "";
		document.getElementById('mDecom').checked = false;
		$('#decomChBox').hide();
}
	//ajax call to edit or create a new room
	$('#myform').on('submit',function(e){
		e.preventDefault();
		$('#editWindow').modal('hide');
		var id = document.getElementById('mId').value;
		var localNum = document.getElementById("mNum").value;
		var roomId = document.getElementById("mRoom").value;
		var room=null;
		var decom = document.getElementById("mDecom").checked;
		room = {id: roomId, number: $('#mRoom :selected').text()};
		var typeId = document.getElementById("mType").value;
		var typeName = $('#mType :selected').text();
		var type = {id: typeId, name: typeName};
		var eqpt = {id: id, localNumber: localNum, decommissioned: decom, eqptType: type, room: room};
		var address = '/lms/api/updateEquipment';
		if(id=="")address = '/lms/api/saveEquipment';
		$.ajax({
		  type: "POST",
		  url: address,
		  data: JSON.stringify(eqpt),
		  contentType: "application/json; charset=utf-8",
			success: function (equipment) {
				if(equipment!=null){
					var room;
					var order = "";
					if(equipment.decommissioned) order = no;
						if(equipment.room!=null)room = equipment.room;
						else room = {id: "n", number: ""};
					if(document.getElementById(equipment.id)==null)	{
						var rowIndex = $('#eqTable').dataTable().fnAddData([equipment.id, room.number, equipment.localNumber, equipment.eqptType.name, order, '<input class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" type="button" onclick="edit(\'' + equipment.localNumber + '\', \'' + equipment.id + '\', \'' + equipment.eqptType.id + '\', \'' + room.id + '\', \'' + equipment.decommissioned + '\')" value="Edit"/>',  room.id]);
						var row = $('#eqTable').dataTable().fnGetNodes(rowIndex);
						$(row).attr('id', equipment.id);
					}
					else $('#eqTable').DataTable().row(document.getElementById(equipment.id)).data([equipment.id, room.number, equipment.localNumber, equipment.eqptType.name, order, '<input class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" type="button" onclick="edit(\'' + equipment.localNumber + '\', \'' + equipment.id + '\', \'' + equipment.eqptType.id + '\', \'' + room.id + '\', \'' + equipment.decommissioned + '\')" value="Edit"/>', room.id]).draw();
				}else {
					$('#errMessage').text("Changes could not have been saved. Please try again.");
					$('#editWindow').modal('show');
					$('#error').modal('show');
				}
          },
			error: function(xhr, status, error) {
					$('#errMessage').text("Something went wrong, the changes were not saved. Please try again.");
					$('#error').modal('show');
			}
		});
	});
	//passing equipment info to edit window
  function edit(localNum, id, typeId, roomId, decommissioned) {
	$('#label').text("Edit equipment");  
	document.getElementById('mId').value = id;
    document.getElementById('mNum').value = localNum;
	document.getElementById('mType').value = typeId;
	document.getElementById('mRoom').value = roomId;
	if(decommissioned == 'true')document.getElementById('mDecom').checked = true;
	else document.getElementById('mDecom').checked = false;
	$('#decomChBox').show();
  }
    
  //filtering equipment by room
  $('#room').change(function (){
	  $('#eqTable').DataTable().column(6).search("\\b"+$('#room').val()+"\\b", true, true).draw();
  });
  function getUrlVars()
{
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}
</script>

<%@include file="footer.jsp"%>